config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :projects do
    resources :milestones
  end

  root 'projects#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/milestone.rb
class Milestone < ApplicationRecord
  belongs_to :project
  validates :name, presence: true, uniqueness: true
  validates :person_responsible, presence: true
  validates :completed, inclusion: { in: [ true, false ] }
  validates :project_id, presence: true
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :milestones
  validates :name , presence: true, uniqueness: true
  validates :person_responsible, presence: true
  validates :project_start_date, presence: true
  validates :planned_termination_date, presence: true

  def progress
    @progress ||= if self.milestones.exists?
      (self.milestones.where("completed = ?", true).length).to_f / (self.milestones.length).to_f * 100.to_f
    else
      0
    end
  end

end
WillPaginate.per_page = 10

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/milestones_controller.rb
class MilestonesController < ApplicationController
  before_action :load_project
  before_action :authenticate_user!, only:[:new, :edit, :destroy]

    def new
      @milestone = @project.milestones.new()  
    end

    def edit
      @milestone = @project.milestones.find(params[:id])
    end

    def create
      @milestone = @project.milestones.new(milestone_params)
      if @milestone.save
        redirect_to @project
      else
        render 'new'
      end
    end

    def update
      @milestone = @project.milestones.find(params[:id])
      if @milestone.update_attributes(milestone_params)
        redirect_to @project
      else
        render 'edit'
      end
    end

    def destroy
      @project.milestones.find(params[:id]).destroy
      redirect_to @project
    end


  private

      def load_project
        @project = Project.find(params[:project_id])
      end

      def milestone_params
        params.require(:milestone).permit(:name, :person_responsible, :description,
                                     :completed)
      end
  end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!, only:[:new, :edit, :destroy]

  def index
    @projects = Project.all.paginate(page: params[:page])
  end

  def new
    @project = Project.new
  end

  def show
    @project = Project.find(params[:id])
  end

  def create
    @project = Project.new(project_params)
    if @project.save
      redirect_to @project
    else
      render 'new'
    end
  end

  def edit
    @project = Project.find(params[:id])
  end

  def update
    @project = Project.find(params[:id])
    if @project.update_attributes(project_params)
      redirect_to @project
    else
      render 'edit'
    end
  end


  def destroy
    Project.find(params[:id]).destroy
    redirect_to root_path
  end

private

    def project_params
      params.require(:project).permit(:name, :person_responsible, :project_start_date, :planned_termination_date, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/milestones_helper.rb
module MilestonesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper

end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
 <div class="container">
   <%= link_to "Projector", root_path, id: "logo" %>
   <nav>
     <ul class="nav navbar-nav navbar-right">
      <% if user_signed_in? %>
        <li><%= link_to current_user.email, '#'%></li>
        <li><%= link_to "Logout",   destroy_user_session_path, method: :delete %></li>
      <% else %>
        <li><%= link_to "Log in",   new_user_session_path %></li>
        <li><%= link_to "Sign up",   new_user_registration_path %></li>
      <% end %>
     </ul>
   </nav>
 </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%=yield(:title)%></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render '/layouts/header' %>
    <div class='container'>
      <%= yield %>
    </div>
  </body>
</html>

app/views/milestones/_form.html.erb
<%=form_for(special_path) do |f| %>
 <% if @milestone.errors.any? %>
  <div class="alert alert-danger" role="alert"><%=@milestone.errors.full_messages%></div>
 <%end%>

  <%= f.label "Name" %>
  <%= f.text_field :name %>

  <%= f.label "Person Responsible" %>
  <%= f.text_field :person_responsible %>

  <%= f.label "Description" %>
  <%= f.text_area :description %>

  <%= f.label "Progress"%>
  <label class= "radio-inline">
    <%= f.radio_button :completed, true, class: "radio-inline" %> Done
  </label>
  <label class= "radio-inline">
    <%= f.radio_button :completed, false, class: "radio-inline"  %> In Progress
  </label>
  <%= f.submit yield(:title), class: "btn btn-primary" %>
<% end %>

app/views/milestones/edit.html.erb
<% provide(:title, 'Edit Milestones')%>
<h2><%=yield(:title)%></h2>
<div class='row'>
  <div class="col-md-6">
    <%= render partial: 'form', :locals => {:special_path => [@project, @milestone]} %>
  <div>
</div>

app/views/milestones/index.html.erb
<div class='row'>
  <div class= 'col-md-12'>
      <% @project.milestones.each do |p| %>
        <h4><%=p.name%></h4>
        <dl class="dl-horizontal list-group-item <%="list-group-item-success" if p.completed %>">
          <dt>Person Responsible:</dt> <dd><%=p.person_responsible%><dd>
          <dt>Description:</dt><dd><%=p.description%></dd>
          <dt>Done:</dt>
          <dd>
            <span class= "<%="glyphicon glyphicon-remove" if !p.completed%>"></span>
            <span class= "<%="glyphicon glyphicon-ok" if p.completed%>"></span>
          </dd>
          <% if user_signed_in? %>
            <dd><%=link_to 'Edit', [:edit, @project, p], class:"btn btn-default"%>
              <%=link_to 'Delete',  [@project,p], method: :delete,
                data: {confirm:"You sure?"} ,class:"btn btn-default"%></dd>
          <% end%>
        </dl>
      <% end%>
      <% if user_signed_in? %>
        <%= link_to "Add Milestone", new_project_milestone_path(@project), class:"btn btn-default"  %>
      <% end %>
  </div>
</div>

app/views/milestones/new.html.erb
<% provide(:title, 'New Milestone')%>
<h2><%=yield(:title)%></h2>
<div class='row'>
  <div class="col-md-6">
    <%= render :partial => 'form', :locals => {:special_path => [@project, @project.milestones.build]} %>
  </div>
</div>

app/views/projects/_form.html.erb
<%=form_for(@project) do |f| %>
  <%= f.label "Name" %>
  <%= f.text_field :name %>

  <%= f.label "Responsible Person" %>
  <%= f.text_field :person_responsible %>

  <%= f.label "Start Date" %>
  <%= f.datetime_field :project_start_date, 'data-provide':'datepicker', 'data-date-format':'dd-mm-yyyy' %>

  <%= f.label "Planned Termination Date" %>
  <%= f.datetime_field :planned_termination_date, 'data-provide':'datepicker', 'data-date-format':'dd-mm-yyyy' %>

  <%= f.label "Description" %>
  <%= f.text_area :description %>

  <%= f.submit yield(:title), class: "btn btn-primary" %>
    <% end %>

app/views/projects/edit.html.erb
<% provide(:title, 'Edit Project')%>
<h2><%=yield(:title)%></h2>
<div class='row'>
  <div class="col-md-6">
    <%= render 'form' %>
  <div>
</div>

app/views/projects/index.html.erb
<% provide(:title, 'Home') %>
<div class='row'>
  <div class= 'col-md-6'>
    <%= will_paginate %>
    <ul class="list-group">
      <% @projects.each do |f| %>
        <%= link_to f.name,   project_path(f), class:"list-group-item" %>
        <div class="progress">
          <div class="progress-bar <%= "progress-bar-success" if f.progress == 100.00 %>" role="progressbar" aria-valuenow="<%=f.progress %>"
            aria-valuemin="0" aria-valuemax="100" style="width:<%=f.progress%>%">
            <span><%=number_to_percentage(f.progress, precision:0)%></span>
          </div>
        </div>
      <% end%>
    </ul>
    <% if user_signed_in? %>
      <%= link_to "Add Project", new_project_path, class:"btn btn-default"  %>
    <% end %>
    <%= will_paginate %>
  </div>
</div>

app/views/projects/new.html.erb
<% provide(:title, 'New Project')%>
<h2><%=yield(:title)%></h2>
<div class='row'>
  <div class="col-md-6">
    <%= render 'form' %>
  <div>
</div>

app/views/projects/show.html.erb
<% provide(:title, @project.name)%>
<h1><%= yield(:title) %></h1>
<div class='row'>
  <div class = 'col-md-6'>
    <h2>Projectinformations</h2>

    <dl class="dl-horizontal">
      <dt>Responsible Person:</dt> <dd><%=@project.person_responsible%></dd>
      <dt>Start Date:</dt> <dd><%=l(@project.project_start_date) %></dd>
      <dt>Planned Termination Date:</dt> <dd><%=l(@project.planned_termination_date) %></dd>
      <dt>Projectprogress:</dt> <dd> <%= number_to_percentage(@project.progress, precision: 2)%></dd>
      <dt>Description:</dt> <dd> <%= @project.description %></dd>
    </dl>

    <div class = 'col-md-6'>
      <% if user_signed_in? %>
        <%= link_to "Edit", edit_project_path(@project), class:"btn btn-default" %>
        <%= link_to "Delete", @project, method: :delete,
              data: {confirm:"You sure?"},
              class:"btn btn-default" %>
      <% end %>
    </div>
  </div>

  <div class= 'col-md-6'>
    <h2>Milestones</h2>
    <%= render template: "/milestones/index.html.erb"%>
  </div>
</div>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>